name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the 'master' branch

jobs:
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    environment: development  # Specify the git hub environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # Specify Dockerfile path
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-repo:1.0